output: outputs/ccle
dataset:
    dataset_home: /Users/jefft/Desktop/p53_project/datasets/CCLE/ccle_broad_2019
    has_log_ed: FALSE
    case_complete_nm: cases_sequenced.txt
    exp_nm: data_mrna_seq_rpkm.txt
    na.str: 
#    has_log_ed: TRUE
#    exp_nm: data_mrna_seq_v2_rsem_zscores_ref_normal_samples.txt
#    na.str: NA

preprocess:
#    norm_gene: GAPDH,ACTB
    quantile: TRUE  # TCGA data has already been batch-corrected, but a quantile norm can be followed by house-keeping gene norm. 
    z_score: TRUE
#    rm_low_expr_gene: -10
    rm_low_expr_gene: 1

eQTL:
    genepos: /Users/jefft/Desktop/p53_project/scripts/eQTL/hg19_gene_table_autosome.tsv
    covariate_from_meta: AGE,SEX
    covariate_code: GENO
#    meta_mut: 
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/Walerych2016.txt
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/breast_COSMIC.txt
