output: outputs/ccle
dataset:
    dataset_home: /Users/jefft/Desktop/p53_project/datasets/CCLE/ccle_broad_2019
    case_complete_nm: cases_sequenced.txt
    has_log_ed: FALSE
    exp_nm: data_mrna_seq_rpkm.txt
    na.str: 
#    has_log_ed: TRUE
#    exp_nm: data_mrna_seq_rpkm_zscores_ref_diploid_samples.txt
#    na.str: NA

preprocess:
    quantile: TRUE
    z_score: TRUE
    diploid_norm: FALSE
    rm_low_expr_gene: -1000

eQTL:
    genepos: /Users/jefft/Desktop/p53_project/scripts/eQTL/hg19_gene_table_autosome.tsv
    covariate_from_meta: AGE,SEX
    covariate_code: GENO
#    meta_mut: 
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/Walerych2016.txt
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/breast_COSMIC.txt
