dataset:
    dataset_home: /Users/jefft/Desktop/p53_project/datasets/BRCA-TCGA/brca_tcga_pan_can_atlas_2018
    case_complete_nm: cases_complete.txt
    exp_nm: data_mrna_seq_v2_rsem.txt
    cna_nm: data_cna.txt
    mut_nm: data_mutations.txt
    gene_col_nm: Hugo_Symbol
    sample_meta_nm: data_clinical_sample.txt
    case_list_dir_nm: case_lists
    na.str: 

eQTL:
    output_file_name_tra: 
    output_file_name_cis: 
    maf_sample_col_nm: Tumor_Sample_Barcode # column name in MAF file referring the sample ID.
    genes: TP53  # which genes SNP located in should be considered, if blank, will consider all SNP. Comma separated.
    genepos: /  # gene location table specific to the version of genome assembly
    pvOutputThreshold: 5e-2
    pvOutputThreshold_cis: 5e-2
    pvOutputThreshold_tra: 5e-2
    cisDist: 1e6
    model: LINEAR
