output: outputs/metabric
dataset:
    dataset_home: /Users/jefft/Desktop/p53_project/datasets/METABRIC/brca_metabric
    exp_nm: data_mrna_agilent_microarray.txt
    na.str: NA

eQTL:
    genepos: /Users/jefft/Desktop/p53_project/scripts/eQTL/hg18_gene_table_autosome.tsv
    covariate_from_meta: ER_STATUS
