output: outputs/tcga_coad_raw_seq
dataset:
    dataset_home: /Users/jefft/Desktop/p53_project/datasets/4-COAD-TCGA/coadread_tcga_pan_can_atlas_2018
    has_log_ed: FALSE
    exp_nm: data_mrna_seq_v2_rsem.txt
    na.str: NA

preprocess:
    quantile: FALSE
    z_score: TRUE
    rm_low_expr_gene: 1
    diploid_norm: FALSE

eQTL:
    genepos: /Users/jefft/Desktop/p53_project/scripts/eQTL/hg19_gene_table.tsv
    # covariate_from_meta: AGE,SEX,ANEUPLOIDY_SCORE
    covariate_from_meta: AGE,SEX
    covariate_code: GENO
    meta_mut: 
     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/hot_spot.txt
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/hot_spot_sub.txt
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/cons.txt
     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/ContactCore.txt
#     - /Users/jefft/Desktop/p53_project/datasets/meta_muts/pos.txt
